from __future__ import annotations

SUSPICIOUS_TLDS = {
    "zip",
    "mov",
    "top",
    "xyz",
    "click",
    "country",
    "kim",
    "gq",
    "tk",
    "ml",
    "cf",
    "work",
    "rest",
    "live",
    "support",
    "quest",
    "cam",
}

SHORTENER_DOMAINS = {
    "bit.ly",
    "tinyurl.com",
    "t.co",
    "goo.gl",
    "ow.ly",
    "is.gd",
    "buff.ly",
    "cutt.ly",
    "shorturl.at",
    "rebrand.ly",
    "lnkd.in",
    "s.id",
}

POPULAR_DOMAINS = {
    "google.com",
    "youtube.com",
    "facebook.com",
    "instagram.com",
    "github.com",
    "gitlab.com",
    "microsoft.com",
    "microsoftonline.com",
    "office.com",
    "apple.com",
    "icloud.com",
    "amazon.com",
    "reddit.com",
    "wikipedia.org",
    "x.com",
    "twitter.com",
    "linkedin.com",
    "paypal.com",
    "stripe.com",
    "netflix.com",
    "openai.com",
    "cloudflare.com",
    "github.io",
    "python.org",
    "pypi.org",
    "stackoverflow.com",
}

LEGITIMATE_DOMAINS = {
    "google.com",
    "accounts.google.com",
    "youtube.com",
    "github.com",
    "github.io",
    "gitlab.com",
    "microsoft.com",
    "microsoftonline.com",
    "office.com",
    "live.com",
    "apple.com",
    "appleid.apple.com",
    "icloud.com",
    "paypal.com",
    "stripe.com",
    "amazon.com",
    "facebook.com",
    "instagram.com",
    "linkedin.com",
    "reddit.com",
    "openai.com",
    "cloudflare.com",
    "python.org",
    "pypi.org",
    "stackoverflow.com",
}

BRAND_DOMAINS = {
    "google.com": ["google", "g00gle", "googIe"],
    "github.com": ["github", "githab", "git-hub"],
    "gitlab.com": ["gitlab", "git-lab"],
    "paypal.com": ["paypal", "paypaI", "pay-pal"],
    "microsoft.com": ["microsoft", "micros0ft"],
    "apple.com": ["apple", "appIe"],
    "instagram.com": ["instagram", "instagrarn"],
    "facebook.com": ["facebook", "facebo0k"],
    "openai.com": ["openai", "chatgpt"],
}

SUSPICIOUS_KEYWORDS = {
    "login",
    "signin",
    "verify",
    "verification",
    "password",
    "passwd",
    "reset",
    "token",
    "session",
    "auth",
    "account",
    "bank",
    "wallet",
    "invoice",
    "payment",
    "confirm",
    "secure",
    "security",
    "update",
    "support",
    "unlock",
    "limited",
    "suspend",
    "blocked",
    "recover",
    "airdrop",
    "crypto",
    "bonus",
    "gift",
    "prize",
    "delivery",
    "track",
    "tracking",
    "shipment",
    "parcel",
}

TRACKING_PARAMS = {
    "utm_source",
    "utm_medium",
    "utm_campaign",
    "utm_term",
    "utm_content",
    "fbclid",
    "gclid",
    "yclid",
    "mc_cid",
    "mc_eid",
}

SENSITIVE_PARAMS = {
    "token",
    "access_token",
    "auth",
    "session",
    "sid",
    "password",
    "pass",
    "email",
    "phone",
    "redirect",
    "return",
    "next",
    "continue",
    "code",
    "otp",
    "pin",
}

SUSPICIOUS_CONTENT_KEYWORDS = {
    "password",
    "verify your account",
    "confirm your account",
    "update your payment",
    "security check",
    "account suspended",
    "limited access",
    "seed phrase",
    "recovery phrase",
    "private key",
    "one-time code",
    "otp",
}